### ref https://jojoldu.tistory.com/266

### create user
POST http://localhost:8080/v1/user
Content-Type: application/json

{
  "userId": "id",
  "userName": "test",
  "userPassword": "test123"
}

### get user
GET http://localhost:8080/v1/user/1

###